var data = require('./data')

console.log('in words')
var threeLetterWords = "AbyAnyBayBeyBoyBuyCayCoyCryDayDeyDryFayFeyFlyFoyFryGayGeyGoyGuyHayHeyHoyIcyIvyJayJoyKayKeyLayLeyMayNayOxyPayPlyPryRaySayShySkySlySoySpyStyThyToyTryWayWhyWryYay"
var allThreeLetterWords = "aahaalaasabaaboabsabyaceactaddadoadsadzaffaftagaageagoagsahaahiahsaidailaimainairaisaitalaalbaleallalpalsaltamaamiampamuanaandaneaniantanyapeapoappaptarbarcarearfarkarmarsartashaskaspassateattaukavaaveavoawaaweawlawnaxeayeaysazobaabadbagbahbalbambanbapbarbasbatbaybedbeebegbelbenbesbetbeybibbidbigbinbiobisbitbizboabobbodbogboobopbosbotbowboxboybrabrobrrbubbudbugbumbunburbusbutbuybyebyscabcadcamcancapcarcatcawcayceecelcepchicigciscobcodcogcolconcoocopcorcoscotcowcoxcoycozcrucrycubcudcuecumcupcurcutcwmdabdaddagdahdakdaldamdandapdawdaydebdeedefdeldendevdewdexdeydibdiddiedifdigdimdindipdisditdocdoedogdoldomdondordosdotdowdrydubdudduedugduhduidunduodupdyeeareateauebbecuedhedseekeeleffefsefteggegoekeeldelfelkellelmelsemeemsemuendengenseoneraereergernerrersessetaetheveeweeyefabfadfagfanfarfasfatfaxfayfedfeefehfemfenferfesfetfeufewfeyfezfibfidfiefigfilfinfirfitfixfizfluflyfobfoefogfohfonfopforfoufoxfoyfrofryfubfudfugfunfurgabgadgaegaggalgamgangapgargasgatgaygedgeegelgemgengetgeyghigibgidgiegiggingipgitgnugoagobgodgoogorgosgotgoxgoygulgumgungutguvguygymgyphadhaehaghahhajhamhaohaphashathawhayhehhemhenhepherheshethewhexheyhichidhiehimhinhiphishithmmhobhodhoehoghonhophoshothowhoyhubhuehughuhhumhunhuphuthypiceichickicyidsiffifsiggilkillimpinkinninsionireirkismitsivyjabjagjamjarjawjayjeejetjeujewjibjigjinjobjoejogjotjowjoyjugjunjusjutkabkaekafkaskatkaykeakefkegkenkepkexkeykhikidkifkinkipkirkiskitkoakobkoikopkorkoskuekyelablacladlaglamlaplarlaslatlavlawlaxlaylealedleelegleileklesletleulevlexleylezliblidlielinliplislitlobloglooloplotlowloxluglumluvluxlyemacmadmaemagmanmapmarmasmatmawmaxmaymedmegmelmemmenmetmewmhomibmicmidmigmilmimmirmismixmoamobmocmodmogmolmommonmoomopmormosmotmowmudmugmummunmusmutmycnabnaenagnahnamnannapnawnaynebneenegnetnewnibnilnimnipnitnixnobnodnognohnomnoonornosnotnownthnubnunnusnutoafoakoaroatobaobeobiocaodaoddodeodsoesoffoftohmohoohsoilokaokeoldoleomsoneonoonsoohootopeopsoptoraorborcoreorsortoseoudouroutovaoweowlownoxooxypacpadpahpalpampanpapparpaspatpawpaxpaypeapecpedpeepegpehpenpepperpespetpewphiphtpiapicpiepigpinpippispitpiupixplypodpohpoipolpompoopoppotpowpoxproprypsipstpubpudpugpulpunpuppurpusputpyapyepyxqatqisquaradragrahrairajramranraprasratrawraxrayrebrecredreerefregreiremrepresretrevrexrhoriaribridrifrigrimrinriprobrocrodroeromrotrowrubruerugrumrunrutryaryesabsacsadsaesagsalsapsatsausawsaxsayseasecseesegseiselsensersetsewsexshasheshhshysibsicsimsinsipsirsissitsixskaskiskyslysobsodsolsomsonsopsossotsousowsoxsoyspaspysristysubsuesuksumsunsupsuqsyntabtadtaetagtajtamtantaotaptartastattautavtawtaxteatedteetegteltentettewthethothytictietiltintiptistittodtoetogtomtontootoptortottowtoytrytsktubtugtuituntuptuttuxtwatwotyeudoughukeuluummumpunsupoupsurburdurnurpuseutauteutsvacvanvarvasvatvauvavvawveevegvetvexviavidvievigvimvisvoevowvoxvugvumwabwadwaewagwanwapwarwaswatwawwaxwaywebwedweewenwetwhawhowhywigwinwiswitwizwoewogwokwonwoowopwoswotwowwrywudwyewynxisyagyahyakyamyapyaryawyayyeayehyenyepyesyetyewyidyinyipyobyodyokyomyonyouyowyukyumyupzagzapzaszaxzedzeezekzepzigzinzipzitzoazoozuzzzz"
var allTwoLetterWords = "aaabadaeagahaialamanarasatawaxaybabebibobydedoedefehelemeneresetexfafegohahehihmhoidifinisitjokakilalilomamemimmmomumynanenonuodoeofohoiomonoporosowoxoypapepiqireshsisotatitouhumunupusutwewoxixuyayeyoza"
var fourLetterWords = "AblyAchyAeryAglyAhoyAiryAlkyAllyArmyArtyAshyAwayAwnyAwryBabyBevyBodyBogyBonyBoxyBrayBuoyBuryBusyCagyCakyCavyChayCityClayCloyCokyColyConyCopyCoryCosyCowyCozyDavyDefyDemyDenyDewyDexyDidyDobyDogyDopyDoryDotyDoxyDozyDrayDulyDutyEasyEddyEdgyEelyEeryEggyElmyEmmyEnvyEspyEyryFlayFleyFogyFoxyFozyFrayFumyFuryGabyGamyGapyGleyGobyGoryGrayGreyHazyHolyHomyIckyIdlyIffyIllyImmyInbyInkyInlyJivyJoeyJokyJuryLacyLadyLakyLazyLevyLilyLimyLinyLogyLoryLunyManyMazyMiryMityMolyMonyMopyNaryNavyNixyNosyOakyObeyOfayOilyOkayOldyOnlyOozyOrbyOrgyPacyPalyPatyPilyPinyPipyPityPixyPlayPloyPogyPokyPolyPonyPosyPoxyPrayPreyPunyQuayQueyRacyRelyRimyRopyRosyRubyRulySagyScrySexyShaySizySlaySpaySpryStaySteySwayTheyTidyTinyTivyTobyTodyTonyToryTowyTrayTreyTroyTypyUglyUndyUpbyVaryVeryVinyWadyWalyWanyWaryWavyWaxyWheyWilyWinyWiryZany"

var splitWordString = function(input, number){
  var output = [];
  for (var i = 0; i < input.length; i += number) {
    var localword = ""
    for (var j = 0; j < number; j++) {
      localword += input[i+j]
    };
    localword = localword.toLowerCase();
    output.push(localword)
    var localword = ""
  };
  return output;
}

console.log(splitWordString(allTwoLetterWords, 2))
// console.log(splitWordString(threeLetterWords, 3))
// console.log(splitWordString(fourLetterWords, 4))
// console.log(splitWordString(allThreeLetterWords, 3))



var firstThreeEqual = function(arrayOne, arrayTwo){
  var output = {}
  for (var i = 0; i < arrayOne.length; i++) {
    for (var j = 0; j < arrayTwo.length; j++) {
      // var a = arrayOne[i].slice(0,3)
      // var b = arrayTwo[j].slice(0,3)
      // console.log('arrayOne[i]', a)
      // console.log('arrayTwo[j]', b)
      if (arrayOne[i].slice(0,3) == arrayTwo[j].slice(0,3)){

        output[arrayOne[i]] = arrayTwo[j]
      }
    };
  };
  return output;
}

console.log(firstThreeEqual(['all'],['ally']))
console.log(firstThreeEqual(data.allThreeLetterWordsArray,data.fourLetterWordsArray))
